# Generated by Django 5.1.1 on 2024-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'get_latest_by': 'published_date', 'ordering': ['published_date']},
        ),
        migrations.AddField(
            model_name='book',
            name='managed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='registered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author'], name='title_auth_index'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('registered', True)), fields=('title',), name='unique_book_registered'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
